version: '3.1'
services:
  nextdom-deb:
    devices:
    #Devices to access if -u is used, please update docker-compose-devices.yml to use device you set.
    #Zigate
    - DUSB=/dev/ttyUSB0:/dev/ttyUSB0
    #zwave
    - DACM=/dev/ttyACM0:/dev/ttyACM0
    - DAMA=/dev/ttyAMA0:/dev/ttyAMA0
