version: '3.1'
services:
  web:
    image: edgd1er/nextdom-web:latest
    #image: edgd1er/nextdom-web.slim:latest
    #build:
    #      dockerfile: apache/Dockerfile
    #      context: .
    #      args:
    #      - initShdef=$initSh
    #      - PHPVERdef=$PHPVER
    #      - VERSIONdef=$VERSION
    #      - BRANCHdef=$BRANCH
    #      - aptcacher=""
    #command: ["/root/init.sh"]
    env_file:
      - envWeb
      - .env
    environment:
      - POSTINST_DEBUG=-v
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost/public/here.html"]
      interval: 10s
      timeout: 10s
    networks:
      nextdom_network:
        aliases:
          - web
    labels:
      - com.centurylinklabs.watchtower.enable=false
    expose:
      - "80"
      - "443"
    ports:
      - "9280:80"
      - "9643:443"
    volumes:
      #- wwwdata-prod:/var/www/html/
      - ./:/root/export/
      - tmptmpfs:/tmp/
    #tmpfs:
    #- /var/log/
    #- /var/www/html/log/
    #- /tmp/nextdom/
    depends_on:
      - mysql

  mysql:
    image: mariadb/server
    #build:
    #  dockerfile: Dockerfile.mysql
    #  context: .
    restart: unless-stopped
    env_file:
      - envMysql
    expose:
      - "3306"
    ports:
      - "3336:3306"
    #volumes:
    #  - mysqldata-prod:/var/lib/mysql
    networks:
      nextdom_network:
        aliases:
          - mysql

  nextdom-adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "9281:8080"
    networks:
      nextdom_network:
        aliases:
          - adminer

volumes:
  mysqldata-prod:
  #    external: true
  wwwdata-prod:
  #    external: true
  tmptmpfs:
    driver_opts:
      device: tmpfs
      type: tmpfs
networks:
  nextdom_network: